version: 2

run:
  timeout: 10m
  go: '1.24'

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 2
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy
      - singleCaseSwitch
      - ifElseChain
      - dupImport
      - octalLiteral
  
  lll:
    line-length: 140
  
  misspell:
    locale: US
  
  revive:
    severity: warning
    rules:
      - name: exported
        arguments: [checkPrivateReceivers]
      - name: var-naming
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    
    - text: "should have a package comment"
      linters:
        - revive
        - golint
    
    - text: "at least one file in a package should have a package comment"
      linters:
        - staticcheck
    
    - source: "//go:generate"
      linters:
        - lll
  
  exclude-dirs:
    - vendor
    - third_party
  
  exclude-files:
    - ".*\\.pb\\.go$"
  
  max-issues-per-linter: 0
  max-same-issues: 0
